### ISSUE TITLE
Erroneous race reported with lazy_static and thread_local

### ISSUE THREAD

**Issue by jonhoo** [tokio-rs/loom#124]
`loom` panics on the following test case:
```rust
lazy_static::lazy_static! {
    static ref A: AtomicUsize = AtomicUsize::new(0);
}

loom::thread_local! {
    static B: usize = A.load(Relaxed);
}

#[test]
fn load_after_lazy_static() {
    loom::model(|| {
        let t1 = thread::spawn(|| {
            B.try_with(|h| *h).unwrap_or_else(|_| A.load(Relaxed));
        });
        let t2 = thread::spawn(|| {
            B.try_with(|h| *h).unwrap_or_else(|_| A.load(Relaxed));
        });
        t1.join().unwrap();
        t2.join().unwrap();
    });
}
```
Reporting:
```
~~~~~~~~ THREAD 1 ~~~~~~~~
~~~~~~~~ THREAD 0 ~~~~~~~~
~~~~~~~~ THREAD 2 ~~~~~~~~
thread 'main' panicked at '
Causality violation: Concurrent load and mut accesses.
     created: tests/atomic.rs:10:33
    with_mut: thread #1 @ tests/atomic.rs:10:33
        load: thread #2 @ tests/atomic.rs:14:23
```
`atomic.rs:10` is the call to `AtomicUsize::new` for `static ref A` line, and `atomic.rs:14` is the `load` in `static B`.

I _think_ this code should be fine?

**Comment by hawkw** [comment]
My guess, though I might be wrong, is that loom will need to be made aware of `lazy_static` for this to work.

**Comment by jonhoo** [comment]
Yeah, that's what @carllerche said too.
Quoth:
> lazy_static w/ loom is no bueno
> that is probably the problem
> I removed the tracking that would have caught atomics leaking across models
> the lazy_static has to be reset each iteration
