### ISSUE TITLE
Add support for AtomicBool, AtomicU64 etc.

### ISSUE THREAD

**Issue by Ekleog** [tokio-rs/loom#13]
Everything is in the title :) As far as I can see on docs.rs the `Atomic<>` type is not public, meaning that these cannot be implemented outside of `loom`.

**Comment by seanmonstar** [comment]
Yes, please! :D

If anyone wants to, it'd be straight forward to copy what was done for `AtomicUsize` to make the other types.

**Comment by JoshMcguigan** [comment]
I'll give this a try.

**Comment by pickfire** [comment]
This should be solved.

**Comment by reevesPAC** [comment]
ok @JoshMcguigan , I'll follow your example.
