### ISSUE TITLE
cannot access a scoped thread local variable without calling `set` first

### ISSUE THREAD

**Issue by nitishch** [tokio-rs/loom#149]
Running the following code -

```rust
use loom::sync::atomic::AtomicUsize;
use std::sync::atomic::Ordering;
use std::thread;

#[test]
fn main() {
    loom::model(|| {
        let busy = AtomicUsize::new(0);
        thread::spawn(move || busy.swap(1, Ordering::SeqCst));
    });
}
```

results in 

```
running 1 test
thread '<unnamed>' panicked at 'cannot access a scoped thread local variable without calling `set` first', <::std::macros::panic macros>:2:4
```

This is not deterministic either. I see this error message only once in about 5 runs.

I couldn't understand how this error message corresponds to the source code. Is there anything wrong with the code? I couldn't figure out if this error message is an issue with Loom or with the Rust compiler.

Corresponding section from `Cargo.toml`:
```rust
[dependencies]
loom = "0.3.4"
```

Result of `uname -a`:
```
Linux anduin 4.15.0-101-generic #102-Ubuntu SMP Mon May 11 10:07:26 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

Cargo version: `cargo 1.42.0 (86334295e 2020-01-31)`
Rustc version: `rustc 1.42.0 (b8cedc004 2020-03-09)`

**Comment by Darksonn** [comment]
You need to use `loom::thread` to spawn the thread. The reason it doesn't fail every time is because you don't join the thread, so it sometimes doesn't call `swap` before the loom model has exited.

**Comment by nitishch** [comment]
Using `loom::thread::spawn` seems to fix the problem. But the example in the Solution section of https://docs.rs/loom/0.3.4/loom/ uses `thread::spawn` to create a thread.

**Comment by hawkw** [comment]
> Using `loom::thread::spawn` seems to fix the problem. But the example in the Solution section of https://docs.rs/loom/0.3.4/loom/ uses `thread::spawn` to create a thread.

The example uses `loom::thread::spawn`:
![Screenshot_20200615_123003](https://user-images.githubusercontent.com/2796466/84698291-69eb9c00-af04-11ea-8471-e0c07ecf2b23.png)

**Comment by nitishch** [comment]
Oh sorry! My bad. I didn't notice the import.

**Comment by hawkw** [comment]
Maybe there's something we can do to make that more obvious in the docs? A comment or something?

**Comment by nitishch** [comment]
Under **Writing Tests** section, there is this sentence -

```
Tests must use the loom synchronization types, such as Atomic*, Mutex, RwLock, Condvar, thread::spawn, etc.
```

This explicitly says Loom's variant of `thread::spawn` should be used. I think that's good enough and it was my mistake I missed it; not the documentation's :)

**Comment by Darksonn** [comment]
We could change it to
```
loom::thread::spawn(...);
```
instead of separating it with an import?
