### ISSUE TITLE
thread 'test::list' panicked at 'index out of bounds: the len is 7 but the index is 17293822569102704640', /Users/jrmuizel/.cargo/registry/src/github.com-1ecc6

### ISSUE THREAD

**Issue by jrmuizel** [tokio-rs/loom#158]
I get
```
---- test::list stdout ----
thread 'test::list' panicked at 'index out of bounds: the len is 7 but the index is 17293822569102704640', /Users/jrmuizel/.cargo/registry/src/github.com-1ecc6299db9ec823/loom-0.3.4/src/rt/object.rs:361:25
```

when running

```rust
use std::ptr;
use loom::sync::atomic::AtomicPtr;
use loom::sync::atomic::Ordering::{Acquire, Relaxed, Release};
use loom::thread;

struct List {
    next: AtomicPtr<List>,
    prev: AtomicPtr<List>,
}

impl List {
    fn new() -> Box<Self> {
        Box::new(List {
            next: AtomicPtr::new(ptr::null_mut()),
            prev: AtomicPtr::new(ptr::null_mut())
        })
    }
}

fn len(mut next: *mut List) -> i32 {
    let mut count = 0;

    while !next.is_null() {
        count += 1;
        next = unsafe { (*next).next.load(Acquire) };
    }
    count
}

fn del(node: *const List) {
    unsafe {
        let next = (*node).next.load(Acquire);
        let prev = (*node).prev.load(Acquire);
        (*prev).next.store(next, Release);
        if !next.is_null() {
            (*next).prev.store(prev, Release);
        }
    }
}

#[test]
fn list() {
    loom::model(|| {
        let mut first = List::new();
        let mut second = List::new();
        let mut third = List::new();

        first.next.store(second.as_mut(), Release);
        second.prev.store(first.as_mut(), Release);

        second.next.store(third.as_mut(), Release);
        third.prev.store(second.as_mut(), Release);


        let jh = thread::spawn(move || {
            del(third.as_ref());
        });
        del(second.as_ref());

        jh.join().unwrap();
  
        let count = len(first.as_mut());
        assert_eq!(1, count);
    });
}
```

**Comment by Darksonn** [comment]
What is your question? The code appears to be incorrect to me, e.g. if the four loads in the two `del` calls happen before the four stores, then you end up with a two-node list of `first` followed by `third`.

You should also create the raw pointers in the call to `del` from mutable references, as it is unsound to modify anything through a raw pointer created from an immutable reference.

**Comment by jrmuizel** [comment]
> What is your question?

Why is loom panicing in object.rs

> The code appears to be incorrect to me, e.g. if the four loads in the two `del` calls happen before the four stores, then you end up with a two-node list of `first` followed by `third`.

Yeah, that's the incorrect ordering that I was hoping loom would show.

> You should also create the raw pointers in the call to `del` from mutable references, as it is unsound to modify anything through a raw pointer created from an immutable reference.

Are you sure that this applies to data in an UnsafeCell? (e.g. atomics) Miri doesn't complain when a version of this without threads.

**Comment by Darksonn** [comment]
Right, the mutable pointer thing doesn't apply here :sweat_smile:. 

I'm guessing it's because in the case where you get the `first → third` list, the box containing `third` has already been dropped by the thread you moved it into, so inside the `len` function, the call to `load` on `third` will internally read deallocated memory, which happens to contain 17293822569102704640.

**Comment by jrmuizel** [comment]
Ah you're right, I didn't realize third was getting dropped. Fixing that, fixed the problem. Thanks.
