### ISSUE TITLE
Add support for RwLock

### ISSUE THREAD

**Issue by hawkw** [tokio-rs/loom#21]
I notice that `loom::sync` has a [mock implementation of `std::sync::Mutex`](https://github.com/carllerche/loom/blob/master/src/sync/mutex.rs) but lacks a mock `std::sync::RwLock`. It would be nice to be able to test code using read-write locks with `loom`.

**Comment by pop** [comment]
I'm interested in contributing to loom. This seems pretty straight forward if I model the `RwLock` implementation after the `Mutex` version. Mind if I start working on this?

**Comment by pickfire** [comment]
@pop Sure, go ahead!
