### ISSUE TITLE
incorrect semantics for `Thread::unpark` followed by `thread::park`

### ISSUE THREAD

**Issue by hawkw** [tokio-rs/loom#246]
If `std::thread::Thread::unpark` is called _prior_ to a call to `std::thread::park`, the `park` call will return immediately, "consuming" the previous unpark. Per [the documentation](https://doc.rust-lang.org/std/thread/fn.park.html#park-and-unpark):

> The `unpark` method on a `Thread` atomically makes the token available if it wasn’t already. Because the token is initially absent, `unpark` followed by `park` will result in the second call returning immediately.

Loom's version of this API does not have this behavior. It appears that `unpark` only notifies a thread if it is currently `park`ed, and does not influence the next call to `park`.

The following test demonstrates this:
```rust
#[test]
fn park_unpark_loom() {
    loom::model(|| {
        loom::thread::current().unpark();
        loom::thread::park();
        println!("it did not deadlock");
    });
}

#[test]
fn park_unpark_std() {
    std::thread::current().unpark();
    std::thread::park();
    println!("it did not deadlock");
}
```

The `park_unpark_std` test will run to completion and print "it did not deadlock", while the `park_unpark_loom` test panics with a deadlock detection error:

```
running 2 tests
test park_unpark_std ... ok
test park_unpark_loom ... FAILED

failures:

---- park_unpark_loom stdout ----
unpark
park
thread 'park_unpark_loom' panicked at 'deadlock; threads = [(Id(0), Blocked)]', src/rt/execution.rs:209:13
stack backtrace:
   ...
```

**Comment by hawkw** [comment]
It looks like the `Notify` type has this behavior, but the `loom::thread` API does not. The `Notify` type's documentation explains that it can be used to mock out park/unpark primitives...which is nice, but sometimes the code being tested _is_ a park/unpark primitive. :)

**Comment by faern** [comment]
I assume this is because `Thread::unpark` early returns and does nothing when called from its own thread. It should still set the threads token.

https://github.com/tokio-rs/loom/blob/555b52fdb267964f0950a52be87b0f28c40b054c/src/rt/thread.rs#L258-L261
