### ISSUE TITLE
Remove tests/spec.rs from crate, which appears to be CC-BY-SA and GFDL

### ISSUE THREAD

**Issue by erickt** [tokio-rs/loom#288]
According to the header on [tests/spec.rs](https://github.com/tokio-rs/loom/blob/master/tests/spec.rs), this was converted from the [C11 spec](https://en.cppreference.com/w/cpp/atomic/memory_order), and according to their [FAQ](https://en.cppreference.com/w/Cppreference:FAQ) carries a CC-BY-SA, and the GFDL license. Could this be removed since it doesn't appear to fall under the top level MIT license?

**Comment by carllerche** [comment]
Thanks for the report, the context, amount, and method of the "conversion" is not sufficient to make it a license violation. The spec was not copied, nor is the test a derivation in substance. Instead, it is using the information in the spec to create a test.
